/*
 * PORT_config.h
 *
 *  Created on: Jan 13, 2020
 *      Author: Mahmoud Fawzy
 */

#ifndef PORT_CONFIG_H_
#define PORT_CONFIG_H_

/* Option DIO_PIN_OUTPUT/DIO_PIN_INPUT */
#define DIO_PIN_0_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_1_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_2_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_3_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_4_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_5_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_6_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_7_DIR	DIO_PIN_OUTPUT

#define DIO_PIN_8_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_9_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_10_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_11_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_12_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_13_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_14_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_15_DIR	DIO_PIN_OUTPUT

#define DIO_PIN_16_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_17_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_18_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_19_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_20_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_21_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_22_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_23_DIR	DIO_PIN_OUTPUT

#define DIO_PIN_24_DIR	DIO_PIN_INPUT
#define DIO_PIN_25_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_26_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_27_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_28_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_29_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_30_DIR	DIO_PIN_OUTPUT
#define DIO_PIN_31_DIR	DIO_PIN_OUTPUT


/* Option DIO_PIN_HIGH/DIO_PIN_LOW */
#define DIO_PIN_0_VALUE		DIO_PIN_HIGH
#define DIO_PIN_1_VALUE		DIO_PIN_HIGH
#define DIO_PIN_2_VALUE		DIO_PIN_HIGH
#define DIO_PIN_3_VALUE		DIO_PIN_HIGH
#define DIO_PIN_4_VALUE		DIO_PIN_HIGH
#define DIO_PIN_5_VALUE		DIO_PIN_HIGH
#define DIO_PIN_6_VALUE		DIO_PIN_HIGH
#define DIO_PIN_7_VALUE		DIO_PIN_HIGH

#define DIO_PIN_8_VALUE		DIO_PIN_HIGH
#define DIO_PIN_9_VALUE		DIO_PIN_HIGH
#define DIO_PIN_10_VALUE	DIO_PIN_HIGH
#define DIO_PIN_11_VALUE	DIO_PIN_HIGH
#define DIO_PIN_12_VALUE	DIO_PIN_HIGH
#define DIO_PIN_13_VALUE	DIO_PIN_HIGH
#define DIO_PIN_14_VALUE	DIO_PIN_HIGH
#define DIO_PIN_15_VALUE	DIO_PIN_HIGH

#define DIO_PIN_16_VALUE	DIO_PIN_HIGH
#define DIO_PIN_17_VALUE	DIO_PIN_HIGH
#define DIO_PIN_18_VALUE	DIO_PIN_HIGH
#define DIO_PIN_19_VALUE	DIO_PIN_HIGH
#define DIO_PIN_20_VALUE	DIO_PIN_HIGH
#define DIO_PIN_21_VALUE	DIO_PIN_HIGH
#define DIO_PIN_22_VALUE	DIO_PIN_HIGH
#define DIO_PIN_23_VALUE	DIO_PIN_HIGH

#define DIO_PIN_24_VALUE	DIO_PIN_INPUT
#define DIO_PIN_25_VALUE	DIO_PIN_HIGH
#define DIO_PIN_26_VALUE	DIO_PIN_HIGH
#define DIO_PIN_27_VALUE	DIO_PIN_HIGH
#define DIO_PIN_28_VALUE	DIO_PIN_HIGH
#define DIO_PIN_29_VALUE	DIO_PIN_HIGH
#define DIO_PIN_30_VALUE	DIO_PIN_HIGH
#define DIO_PIN_31_VALUE	DIO_PIN_HIGH
#endif /* PORT_CONFIG_H_ */
